### ISSUE TITLE
Doesn't work on Safari 8.0.2

### ISSUE THREAD

**Issue by jaabble** [hekigan/is-loading#11]
Loading animation don't appear.

**Comment by hekigan** [comment]
Hi,

sorry for my very late reply.

I tested it with Safari 8 on Mac and the loading the does appear as expected.
Are you saying that you don't see the loading/turning graphic? If that's the case, it's normal.
This is a webfont called "font-awesome" and is not included in the script.
You can easily include it though.

All info there: 
http://fortawesome.github.io/Font-Awesome/
