### ISSUE TITLE
browser window - overlay resizing 

### ISSUE THREAD

**Issue by ltdeta** [hekigan/is-loading#12]
using "ui tab" with isloading option "position: overlay"
if browser window is resized also the ui-tab is resized but the overlay not

**Comment by hekigan** [comment]
When you say "ui tab", do you mean jQuery UI library?

**Comment by ltdeta** [comment]
yes

**Comment by adilek** [comment]
Agree. It is not re-sized automatically when window is re-sized.

**Comment by ltdeta** [comment]
any plans for insert this ?

**Comment by hekigan** [comment]
I fixed it, but did not release the update yet.
I will do that tomorrow I think. I want to make some other small changes before commiting.

**Comment by hekigan** [comment]
All done!
