### ISSUE TITLE
Full-Overlay --> I can't use two instances with different texts in Full Screen (full-Overlay)

### ISSUE THREAD

**Issue by MoL0ToV85** [hekigan/is-loading#19]
Hi.

I implemented this plugin with jquery and used it in two instances, loading and saving data. In the data load, this shows me the text that you configure in the options. Then I need to save the data and create other options with another text (for example: Save) for the other instance but, in load (with the new options) this dont change text... both are in full-overlay ($.isLoading(OPTIONS)).

This is the reason:

```
// Constructor
    $.fn[pluginName] = function ( options ) {
        return this.each(function () {
            if ( !$.data( this, "plugin_" + pluginName ) ) {
                $.data( this, "plugin_" + pluginName, new Plugin( this, options ) );
            } else {
                var elt = $.data( this, "plugin_" + pluginName );

                if ("hide" === options) { elt.hide();}
                else                        { elt.show(); }
            }
        });
    };
```

I change for this:

```
// Constructor
    $.fn[pluginName] = function ( options ) {
        return this.each(function () {
            if ( !$.data( this, "plugin_" + pluginName ) ) {
                $.data( this, "plugin_" + pluginName, new Plugin( this, options ) );
            } else {
                var elt = $.data( this, "plugin_" + pluginName );

                if ("hide" === options) { 
                    elt.hide(); 
                    $.removeData(this, "plugin_" + pluginName) 
                }
                else                        { elt.show(); }
            }
        });
    };
```

with this, dont use the old Options ("load" for example).
Browser:
Chrome 59.0.3071.115 x64

**Comment by hekigan** [comment]
Hi!

The tooltip was designed to have only **1 fullscreen overlay** at a time.
I did not account for the fact that someone might want to prepare and hold several instances at the same time.

It's possible to have different text if you do it like this:
https://codepen.io/hekigan/pen/rwgjge

The reason behind that is mostly not to pollute the DOM with a lot of unused tags.

Is there a reason why you might need to keep the loaders instance at all time?
