### ISSUE TITLE
TypeError when remove not active loading screen

### ISSUE THREAD

**Issue by onexing** [hekigan/is-loading#20]
When i use "is-loading" same as:

function blockScreen() {
    isLoading({text: 'Loading...'}).loading();
}

function unBlockScreen() {
    isLoading().remove();
}

/** try to remove isLoading screen without activate **/
unBlockScreen();

browser alert this error:
TypeError: Argument 1 of Node.removeChild is not an object.                isLoading.js:248:13

**Browser Version:
Firefox 57.0.1 (64-bit) linux mint

**Comment by hekigan** [comment]
This is because you are missing an argument in your call.
You don't specify the DOM element.

The use is like so:
```
// $elt = whatever DOM element
// options = {...}

const loader = isLoading($elt, options);
loader.loading();

// or

isLoading($elt, options).loading();
```

**Comment by onexing** [comment]
Maybie i dont understand something but in README.md says: "Full overlay mode is an exception with either no parameters or 1 parameter for the option object." and example "isLoading(options);"

My methods works fine if i use:
blockScreen();
/** then **/
unBlockScreen();

without any errors.

I mean if you create some more checks near error string - this will be work fine.

**Comment by hekigan** [comment]
My bad, you are right and I misunderstood your question:

I put together a quick demo there:
https://codepen.io/hekigan/pen/VyxyzK

If you use the script on a proper order (show, THEN destroy), there is no error.

Your error, indeed, comes up in case you are trying to remove the overlay before it is created.
I did not build a fail-safe for that case yet.

**Comment by onexing** [comment]
Yes! :) Thank you for this plugin!

**Comment by hekigan** [comment]
It's been a while, but I finally got some time to fix this.
The release is v2.0.4
