### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by zsmatyas** [hekigan/is-loading#8]
The code - the generated HTML layout - depends on css files, that are not included in this repository. External files might change without any notice, and they are licensed completely differently then this jquery plugin. So... you wont be able to get similar outlook for your overlays without including those files as well...

**Comment by hekigan** [comment]
A folder called "doc-sample" is included in the zip file.
The base is Bootstrap, and an added CSS is there for the basic design of the loader itself (bottom of the .less file).
