### ISSUE TITLE
Incorrect overlay positioning

### ISSUE THREAD

**Issue by zsmatyas** [hekigan/is-loading#9]
I attempted to use it for an async content download, and I add for example 10 000 lines to the end of the page. The css rules present:

.isloading-overlay .isloading-wrapper { top: 10%; } 

This value with the updated page content of mine means that the overlay is about 1000 * 10% lines from the top, that is way outside of the screen.

**Comment by hekigan** [comment]
It should be fixed in the 1.0.5 release.
